/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Prueba_12.glb --print 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Prueba_12.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.f1b89261_b7f4_436a_9699_bbb45ed431e4.geometry} material={materials.f1b89261_b7f4_436a_9699_bbb45ed431e4} position={[-0.092, 0.02, 0.455]} scale={0.521} />
      <mesh geometry={nodes.tripo_36b1b19c_4880_454a_866f_5fec877cdb5b.geometry} material={materials['tripo_36b1b19c_4880_454a_866f_5fec877cdb5b.001']} position={[-0.132, 0.526, 0.392]} rotation={[-0.269, -0.022, -1.492]} scale={0.075} />
      <mesh geometry={nodes.tripo_86f46718_43c0_4911_b705_7fa8cf1c9a43.geometry} material={materials.tripo_86f46718_43c0_4911_b705_7fa8cf1c9a43} position={[-0.008, 0.523, 0.384]} rotation={[0.073, -0.908, 0.257]} scale={0.098} />
    </group>
  )
}

useGLTF.preload('/Prueba_12.glb')
